# Generated by Django 3.1 on 2020-08-31 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.FileField(upload_to='uploads/')),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('employee', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='authorization.employee')),
            ],
            options={
                'verbose_name_plural': 'Backups',
            },
        ),
    ]
