# Generated by Django 3.0.8 on 2020-10-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.FileField(upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Paths',
            },
        ),
    ]
