# Generated by Django 3.1.2 on 2020-10-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backup',
            name='store',
        ),
        migrations.AddField(
            model_name='backup',
            name='path',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='administration.path'),
        ),
    ]
