# Generated by Django 3.0.8 on 2020-10-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20201017_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='store',
            field=models.FileField(unique=True, upload_to='uploads/'),
        ),
    ]
