# Generated by Django 3.0.8 on 2020-10-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20201022_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='store',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
