# Generated by Django 3.0.8 on 2020-10-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0008_auto_20201022_2212'),
        ('administration', '0006_auto_20201022_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backup',
            name='path',
            field=models.FileField(default='/Dokumente', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Path',
        ),
    ]
