# Generated by Django 3.1 on 2020-08-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=45)),
                ('lastname', models.CharField(blank=True, max_length=45)),
                ('phonenumber', models.CharField(blank=True, max_length=45, unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Customern',
            },
        ),
    ]
