# Generated by Django 3.1.2 on 2020-10-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=45)),
                ('lastname', models.CharField(blank=True, max_length=45)),
                ('birthday', models.DateField(default=None, max_length=45)),
                ('phonenumber', models.DecimalField(blank=True, decimal_places=0, max_digits=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Customern',
            },
        ),
    ]
