# Generated by Django 3.1 on 2020-08-31 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'categorien',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45, null=True)),
                ('factor', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('amount', models.IntegerField(blank=True, default=0)),
                ('begin', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'discounte',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'propertyen',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxrate', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'taxsätze',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('costs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('weight', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('brand', models.CharField(blank=True, max_length=45)),
                ('picture', models.FileField(blank=True, default='mit_img/default.jpg', upload_to='pro_img/')),
                ('type', models.CharField(choices=[('DI', 'Dienstleistung'), ('PR', 'Product')], default='PR', max_length=2)),
                ('category', models.ManyToManyField(blank=True, to='product.Category')),
                ('discount', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount')),
                ('property', models.ManyToManyField(blank=True, to='product.Property')),
                ('tax', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.tax')),
            ],
            options={
                'verbose_name_plural': 'Producte',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
    ]
