# Generated by Django 3.1.1 on 2020-09-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Attribute',
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name_plural': 'attributes'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='property',
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='product.Attribute'),
        ),
    ]
