# Generated by Django 3.1.2 on 2020-10-17 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20201017_1630'),
        ('product', '0006_auto_20201017_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.path'),
        ),
    ]
