# Generated by Django 3.1.2 on 2020-10-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201017_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='path',
        ),
    ]
