# Generated by Django 3.1.2 on 2020-10-17 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_auto_20201017_1630'),
        ('product', '0008_remove_product_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.path'),
        ),
    ]
