# Generated by Django 3.0.8 on 2020-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20201019_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('DI', 'Dienstleistung'), ('PR', 'Produkt')], default='PR', max_length=2),
        ),
    ]
