# Generated by Django 3.0.8 on 2020-10-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_tax_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='path',
            field=models.FileField(blank=True, default=None, null=True, unique=True, upload_to='uploads/'),
        ),
    ]
