# Generated by Django 3.1.2 on 2020-10-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20201021_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribute',
            new_name='Attribut',
        ),
    ]
