# Generated by Django 3.1.2 on 2020-10-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20201021_1808'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attribut',
            new_name='Attribute',
        ),
    ]
