# Generated by Django 3.1.2 on 2020-10-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20201021_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['type'], 'verbose_name_plural': 'Products'},
        ),
    ]
