# Generated by Django 3.0.8 on 2020-10-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20201021_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['type'], 'verbose_name_plural': 'Products'},
        ),
    ]
