# Generated by Django 3.0.8 on 2020-10-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20201021_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-type'], 'verbose_name_plural': 'Products'},
        ),
    ]
