# Generated by Django 3.0.8 on 2020-10-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20201021_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['type'], 'verbose_name_plural': 'Products'},
        ),
    ]
