# Generated by Django 3.0.8 on 2020-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20201021_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='costs',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
