# Generated by Django 3.0.8 on 2020-10-23 10:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20201023_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax',
            name='taxrate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
