# Generated by Django 3.0.8 on 2020-10-23 10:18

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20201023_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='costs',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))]),
        ),
    ]
