# Generated by Django 3.0.8 on 2020-10-23 10:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20201023_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='amount',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))]),
        ),
    ]
