# Generated by Django 3.0.8 on 2020-11-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end',
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
