# Generated by Django 3.0.8 on 2020-11-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzation', '0002_auto_20201105_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='end',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
