# Generated by Django 3.1 on 2020-08-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('username', models.TextField()),
                ('password', models.CharField(max_length=72)),
                ('picture', models.FileField(blank=True, default='static/mit_img/default.jpg', upload_to='mit_img/')),
                ('role', models.CharField(choices=[('KA', 'Kassierer'), ('AD', 'Administrator'), ('AN', 'Analyst')], default='KA', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Mitarbeiter',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PR', 'Passwort zurücksetzen'), ('AC', 'Account anlegen')], max_length=2)),
                ('firstname', models.CharField(blank=True, max_length=45)),
                ('lastname', models.CharField(blank=True, max_length=45)),
                ('password', models.BinaryField(editable=True)),
                ('role', models.CharField(blank=True, choices=[('KA', 'Kassierer'), ('AD', 'Administrator'), ('AN', 'Analyst')], default=None, max_length=2)),
                ('employee', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='authorization.employee')),
            ],
            options={
                'verbose_name_plural': 'Anfragen',
            },
        ),
    ]
