# Generated by Django 3.1.2 on 2020-10-30 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    # dependencies = [
    #     ('auth', '0012_alter_user_first_name_max_length'),
    # ]

    operations = [
        migrations.CreateModel(
            name='Active_Accounts',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=150)),
                ('lastname', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('admin', models.BooleanField(default=False)),
                ('analyst', models.BooleanField(default=False)),
                ('kassierer', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('PR', 'Passwort zurücksetzen'), ('AC', 'Account anlegen')], default='AC', max_length=2)),
            ],
        ),
    ]
