# Generated by Django 3.1.2 on 2020-10-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=150)),
                ('lastname', models.CharField(blank=True, max_length=150)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('admin', models.BooleanField(default=False)),
                ('analyst', models.BooleanField(default=False)),
                ('kassierer', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('PR', 'Passwort zurücksetzen'), ('AC', 'Account anlegen')], default='AC', max_length=2)),
            ],
        ),
    ]
