# Generated by Django 3.1.1 on 2020-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role_select',
            field=models.CharField(choices=[('cashier', 'Kassierer'), ('admin', 'Administrator'), ('analyst', 'Analyst')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.BinaryField(editable=True, max_length=72),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=45),
        ),
    ]
