# Generated by Django 3.1.2 on 2020-10-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20201029_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active_accounts',
            old_name='username',
            new_name='user',
        ),
    ]
