# Generated by Django 3.1.1 on 2020-10-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20200905_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role_select',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
