# Generated by Django 3.1.2 on 2020-10-29 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authorization', '0004_auto_20201029_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_accounts',
            name='id',
        ),
        migrations.AlterField(
            model_name='active_accounts',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
