# Generated by Django 3.0.8 on 2020-10-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_request_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=73),
        ),
        migrations.AlterField(
            model_name='request',
            name='password',
            field=models.CharField(max_length=73),
        ),
    ]
