# Generated by Django 3.1.2 on 2020-10-25 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbox', '0012_auto_20201025_1750'),
        ('analyzation', '0002_auto_20201025_1750'),
        ('administration', '0008_auto_20201025_1750'),
        ('authorization', '0005_auto_20201017_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
