# Generated by Django 3.1.2 on 2020-10-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20201025_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.RemoveField(
            model_name='request',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='request',
            name='password',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requestid',
        ),
        migrations.RemoveField(
            model_name='request',
            name='role',
        ),
        migrations.AddField(
            model_name='request',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='firstname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='request',
            name='lastname',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
