# Generated by Django 3.1.2 on 2020-10-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_auto_20201027_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Active_Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
