# Generated by Django 3.1.2 on 2020-10-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0008_active_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='role',
            field=models.CharField(choices=[('KA', 'Kassierer'), ('AD', 'Administrator'), ('AN', 'Analyst')], default='KA', max_length=2),
        ),
    ]
