# Generated by Django 3.1.2 on 2020-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_request_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='role',
        ),
        migrations.AddField(
            model_name='request',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='analyst',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='kassierer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('PR', 'Passwort zurücksetzen'), ('AC', 'Account anlegen')], default='AC', max_length=2),
        ),
    ]
