# Generated by Django 3.1.2 on 2020-10-30 17:05

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField()),
                ('totalcosts', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('path', models.FileField(blank=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Rechnungen',
            },
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))])),
            ],
            options={
                'verbose_name_plural': 'Cashboxn',
            },
        ),
        migrations.CreateModel(
            name='Paymenttool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('path', models.FileField(blank=True, default=None, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'paymenttool',
            },
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))])),
                ('employee', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tresore',
            },
        ),
        migrations.CreateModel(
            name='ReversalBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField()),
                ('refund', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('path', models.FileField(blank=True, upload_to='uploads/')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.bill')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.cashbox')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stornorechnungen',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.cashbox'),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='paymenttool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cashbox.paymenttool'),
        ),
        migrations.CreateModel(
            name='Bill_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))])),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('bill', 'product')},
            },
        ),
    ]
