# Generated by Django 3.1 on 2020-08-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField()),
                ('totalcosts', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('pdf', models.FileField(blank=True, default='mit_img/default.jpg', upload_to='rec_pdf/')),
            ],
            options={
                'verbose_name_plural': 'Rechnungen',
            },
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'Cashboxn',
            },
        ),
        migrations.CreateModel(
            name='Paymenttool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('picture', models.FileField(blank=True, default='mit_img/default.jpg', upload_to='zah_img/')),
            ],
            options={
                'verbose_name_plural': 'paymenttool',
            },
        ),
        migrations.CreateModel(
            name='Tresor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('employee', models.ManyToManyField(blank=True, to='authorization.Employee')),
            ],
            options={
                'verbose_name_plural': 'Tresore',
            },
        ),
        migrations.CreateModel(
            name='ReversalBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField()),
                ('refund', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7)),
                ('pdf', models.FileField(blank=True, default='mit_img/default.jpg', upload_to='sto_rec_pdf/')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.bill')),
                ('cashbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.cashbox')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.employee')),
            ],
            options={
                'verbose_name_plural': 'Stornorechnungen',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='cashbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.cashbox'),
        ),
        migrations.AddField(
            model_name='bill',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.discount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.employee'),
        ),
        migrations.AddField(
            model_name='bill',
            name='paymenttool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cashbox.paymenttool'),
        ),
        migrations.CreateModel(
            name='Rechnung_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbox.bill')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'unique_together': {('bill', 'product')},
            },
        ),
    ]
