# Generated by Django 3.1 on 2020-08-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('cashbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tresor',
            new_name='Safe',
        ),
    ]
