# Generated by Django 3.1.2 on 2020-10-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('cashbox', '0002_cashbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbox',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='authorization.active_accounts'),
        ),
    ]
