# Generated by Django 3.1 on 2020-08-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('cashbox', '0002_auto_20200831_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rechnung_Product',
            new_name='Bill_Product',
        ),
    ]
