# Generated by Django 3.0.8 on 2020-11-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0003_auto_20201031_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='isReversalbill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='linkedbill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashbox.Bill'),
        ),
    ]
