# Generated by Django 3.0.8 on 2020-11-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0004_auto_20201107_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='refund',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
