# Generated by Django 3.0.8 on 2020-10-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0005_auto_20201017_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttool',
            name='path',
            field=models.FileField(blank=True, default=None, null=True, unique=True, upload_to='uploads/'),
        ),
    ]
