# Generated by Django 3.0.8 on 2020-10-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0006_auto_20201021_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttool',
            name='path',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
