# Generated by Django 3.0.8 on 2020-10-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0007_auto_20201022_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='path',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='reversalbill',
            name='path',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
