# Generated by Django 3.0.8 on 2020-10-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0008_auto_20201022_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='path',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
