# Generated by Django 3.0.8 on 2020-10-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0009_auto_20201023_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversalbill',
            name='path',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
