# Generated by Django 3.0.8 on 2020-10-23 10:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbox', '0010_auto_20201023_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_product',
            name='amount',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))]),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))]),
        ),
        migrations.AlterField(
            model_name='safe',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('-0.01'))]),
        ),
    ]
